### ISSUE TITLE
【feature request】希望可以自定义端口, 自动保存输入的文字.

### ISSUE THREAD

**Issue by digitalstationol** [cornradio/LANwebclipboard-win-flask#1]
谢谢大佬的项目!
希望可以自定义端口,我知道app.py可以更改,尝试在linux和windows编译成功了,但是无法运行.
希望可以自动保存输入的文字,
保存的txt文件是按1.txt 2.txt命名的,能不能给个选项按保存的日期命名.

**Comment by cornradio** [comment]
1. 自定义端口 这个应该可以搞得。加一个配置文件就可以了。
2. 按保存的日期命名 这个不好搞。因为是ai写的 不太清楚在哪里写的有没有很多关联。。。 应该不会做。

**Comment by cornradio** [comment]
自动保存输入的文字 是临时保存输入框内容的意思么？ 这个可以通过前端实现 可以加上。

**Comment by cornradio** [comment]
可以在这里下载最新的自动打包 https://github.com/cornradio/LANwebclipboard-win-flask/actions/runs/12546354862

**Comment by cornradio** [comment]
日期命名 的话 如果希望知道日期，可以直接通过文件管理 按照日期排序查看。
就不加功能了。
issue closed！
